"""Adding column cuisine

Revision ID: 550bcd22fda8
Revises: 
Create Date: 2022-04-14 11:24:10.576880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550bcd22fda8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('cuisine', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_restaurant_cuisine'), 'restaurant', ['cuisine'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_cuisine'), table_name='restaurant')
    op.drop_column('restaurant', 'cuisine')
    # ### end Alembic commands ###
